In [4]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv('wheat_dataset.csv')

In [6]:
df.head()


Year  wheat Demand in million tons  population   per capita income  \
0  2005                         69.35   1154638713           714.8610   
1  2006                         75.81   1172373788           806.7533   
2  2007                         78.57   1189691809          1028.3348   
3  2008                         80.68   1206734806           998.5223   
4  2009                         80.80   1223640160          1101.9608   

   international demand  
0                   801  
1                    94  
2                    49  
3                    23  
4                    58

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 5 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Year                          18 non-null     int64  
 1   wheat Demand in million tons  18 non-null     float64
 2   population                    18 non-null     int64  
 3   per capita income             18 non-null     float64
 4   international demand          18 non-null     int64  
dtypes: float64(2), int64(3)
memory usage: 848.0 bytes


## Spliting dataset into test and train

In [8]:
from sklearn.model_selection import train_test_split
X = df.drop('wheat Demand in million tons',axis=1)
X = X.drop('Year', axis=1)
y = df['wheat Demand in million tons']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [9]:
X_train

population   per capita income  international demand
16   1407563842          2277.4343                  8033
15   1396387127          1933.1011                  2561
5    1240613620          1357.5637                    72
9    1307246509          1573.8856                  3409
0    1154638713           714.8610                   801
10   1322866505          1605.6054                  1130
6    1257621191          1458.1041                   891
17   1417173173          1850.0000                  6500
7    1274487215          1443.8824                  6824
11   1338636340          1732.5542                   501
1    1172373788           806.7533                    94
3    1206734806           998.5223                    23

In [10]:
X_test

population   per capita income  international demand
4    1223640160          1101.9608                    58
12   1354195680          1980.6670                   569
13   1369003306          1998.2591                   496
8    1291132063          1449.6105                  6053
14   1383112050          2072.2449                   509
2    1189691809          1028.3348                    49

In [11]:
y_train

16    110.95
15    109.65
5      86.87
9      86.53
0      69.35
10     92.29
6      94.88
17    112.45
7      93.51
11     98.51
1      75.81
3      80.68
Name: wheat Demand in million tons, dtype: float64

In [12]:
y_test

4      80.80
12     99.87
13    103.60
8      95.85
14    107.59
2      78.57
Name: wheat Demand in million tons, dtype: float64

## Training Model

### 1. Random Forest

In [13]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators=100, random_state=0)
regressor.fit(X_train,y_train)

RandomForestRegressor(random_state=0)

In [14]:
y_pred = regressor.predict(X_test)
y_pred

array([ 82.084 , 102.6485, 105.8006,  92.4443, 106.517 ,  79.7148])

In [15]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9610677606839023

In [16]:
ans = regressor.predict([[1437173180,2500,10000]])
ans

c:\users\vaish\appdata\local\programs\python\python39\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([110.7146])

### 2. Support Vector Machine

In [17]:
from sklearn.svm import SVR
regressor = SVR(kernel='rbf')
regressor.fit(X_train, y_train)

SVR()

In [18]:
y_pred = regressor.predict(X_test)
y_pred

array([92.80932301, 92.96709926, 92.98482782, 92.89086135, 93.00161892,
       92.76893486])

In [19]:
r2_score(y_test, y_pred)

-0.0021439043782556233

In [20]:
ans = regressor.predict([[1437173180,2500,10000]])
ans

c:\users\vaish\appdata\local\programs\python\python39\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(


array([93.06473278])

In [21]:
from sklearn.tree import  DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state=0)
regressor.fit(X_train, y_train)

DecisionTreeRegressor(random_state=0)

In [22]:
y_pred = regressor.predict(X_test)
y_pred
r2_score(y_test, y_pred)

0.7224774369101034

### 3. Multiple Linear Regression

In [23]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [24]:
y_pred = regressor.predict(X_test)
y_pred

array([ 82.09585904, 102.72554187, 104.40069878,  93.04517918,
       106.45852731,  77.96173991])

In [25]:
r2_score(y_test, y_pred)

0.9724702498075387

In [26]:
ans = regressor.predict([[1437173180,2500,7000]])
ans

c:\users\vaish\appdata\local\programs\python\python39\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([116.72021479])

In [27]:
import pickle

In [28]:
pickle.dump(regressor, open('demo.pkl', 'wb'))